import Head from 'next/head';
import Image from 'next/image';
import Login from '../components/Login';
import styles from '../styles/Home.module.css';
import { useMoralis } from "react-moralis";

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();

  if (!isAuthenticated) return <Login />

  return (
    <div className={styles.container}>
      <Head>
        <title>RTT WEB3 SPACE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
        />
        <link rel="stylesheet" href="static/dist/tailwind.css" />
  </head>

      </Head>

      <h1>RTT WEB3 SPACE</h1>
      <button onClick={logout}>Logout</button>
    </div>
  );

}
