import Head from 'next/head';
import Image from 'next/image';
import Login from '../components/Login';
import styles from '../styles/Home.module.css';
import { useMoralis } from "react-moralis";
import Header from "../components/Header";
import Messages from '../components/Messages';

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();

  if (!isAuthenticated) return <Login />

  return (
    <div className="h-screen overflow-y-scroll bg-gradient-to-b from-white to-black overflow-hidden">
      <Head>
        <title>RTT WEB3 SPACE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div 
        className="max-w-screen-l mx-auto">
        {/* Header */}
        <Header />
        {/* Messages */}
        <Messages />
      </div>
    </div>
  );

}
